### ISSUE TITLE
How to run the code？

### ISSUE THREAD

**Issue by ChenhuaYang** [zainmehdi/Optical-Flow-based-Obstacle-Avoidance#1]
Hello, I tried to run the code, but after I enter the commands bellow, nothing happened.
$catkin_create_pkg optical_flow_obstacle_avoidance image_transport  cv_bridge   roscpp  rospy std_msgs
$catkin_make
$rosrun optical_flow_obstacle_avoidance optical_flow_obstacle_avoidance 
 
So how can I get the result as you show in youtube? 
Thanks!

**Comment by zainmehdi** [comment]
did it compile  properly ? if it compiled well you just need to run the executable and make sure the image topic is same as specified in the code
