### ISSUE TITLE
Is there some new progress for more capbility?

### ISSUE THREAD

**Issue by wbzhang233** [zainmehdi/Optical-Flow-based-Obstacle-Avoidance#2]
Hey, I saw you guys published this Repo in 3 years ago, and I test your code, I feel not good. And I achieve the calculation of FOE, but I doubt the feasibility of the method proposed in the  Souhila's paper. This method cannot determine a trajectory.

**Comment by zainmehdi** [comment]
This is just an experimental reactive obstacle avoidance node. It doesnt compute any trajectory at all.
